services:
  # a fully loaded development environment to test new code
  dev:
    &dev
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code

  # run all the tests
  test:
    <<: *dev
    command: pytest -v --cov=. --cov-report term-missing

  black:
    <<: *dev
    command: black .

  play:
    <<: *dev
    command: python stock_game.py

  # run the linters
  # lint:
  #   <<: *dev
  # command: TODO: IMPLEMENT THIS
